---
title: "Financial Crises in Developing Countries"
subtitle: "International Finance 2"
author: "Sergio Béjar"
institute: ""
date: "4/5/2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "xaringan.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(dev ='svg')
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
library(tidyverse)
library(stevemisc)
```

## Stages of Financial Crises in Developing Countries 

### Stage 1: Initiation

**Path one: mismanagement of financial liberalization**
- Weak supervision and lack of expertise.
- Domestic banks borrow from foreign banks. 
- Fixed exchange rates give a sense of lower risk.
- Securities markets not well-developed.

**Path two: severe fiscal imbalances**
- Governments force banks to buy government debt. 
- When government debt loses value, bank net worth down . 
- Additional factors:
- Increase in interest rates (from abroad)
- Asset price decrease
- Uncertainty linked to unstable political systems




---
### Initiation of Financial Crisis 1

**Additional Factors**


- Increase in interest rates (from abroad)
- Asset price decrease
- Uncertainty linked to unstable political systems


---
### Stage 2:  Currency Crisis 

Bank loses lead to currency crisis.

- Governments cannot raise interest rates (doing so forces banks into insolvency)...
- ... and speculators expect a devaluation 
- Foreign and domestic investors sell the domestic currency. 



---
### Stage 3: Full-Fledged Financial Crisis

- The debt burden in terms if domestic currency increases.
- Banks are more likely to fail if: (1) individuals are less able to play of their debts, and (2) debt denominated in foreign currency increases (i.e. value of liabilities increases).

- Routinely, ordinary citizens bear the costs of adjustment.

---
## Financial Crises 
### Mexico (1994-1995)

- Financial liberalization in the early 1990s: Lending boom, coupled with weak supervision and lack of expertise. Banks accumulated losses and their net worth declined.
- Rise in interest rates abroad.
- Uncertainty increased (political instability).
- Domestic currency devaluated on December 20, 1994. 
- Rise in actual and expected inflation. 

---
## Financial Crises
### East Asia (1997-1998)

- Financial liberalization in the early 1990s: Lending boom, coupled with weak supervision and lack of expertise. Banks accumulated losses and their net worth declined.
- Uncertainty increased (stock market declines and failure of prominent firms).
- Domestic currencies devaluated by 1997. 
- Rise in actual and expected inflation.
---

##Financial Crises
###Argentina (2001)

- Government coerced banks to absorb large amounts of debt due to fiscal imbalances_. 
- Rise in interest rates abroad.
- Uncertainty increased (ongoing recession).
- Domestic currency devaluated on January 6, 2002
- Rise in actual and expected inflation.

---