---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
geometry: margin=1in

title: "POLS 155-01: International Political Economy"
author: Sergio Béjar-López
date: "San Jose State University, Spring 2021"

email: "sergio.bejar@sjsu.edu"
web: "sergiobejar.com"
officehours: "W 09:00-11:30 a.m."
office: "453 Clark Hall"
classroom: "*online*"
classhours: "Asynchronous"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

# Catalog Course Description

This course examines how states, international and multinational bodies, and global social movements shape trade, financial, and labor relations. Topics include: international trade and protectionism, the International Monetary Fund and the World Bank, regional integration, and transnational corporations.

# Detailed Course Description

This course will help students to develop a conceptual and empirical background that is necessary to understand globalization and the changes taking place in the international economy.  Our main focus will be to critically analyze some of the most important issues in the current international economic system.  At a broader level, we will study topics such as the politics of trade policy, foreign direct investment, financial crises, and the future of the global economic system.   More specifically, we will analyze the politics of trade conflict at the GATT/WTO, trade reforms in developing countries, the role of multinational corporations in the world economy, the role of international financial institutions like the IMF, and debates over outsourcing and financial crises.  For each topic, we will analyze different theoretical explanations and a variety of historical and contemporary examples. 

*This is an Online Education course. All assignments and exams will be conducted over the Internet. Students are responsible for their own access to the Internet and computer resources.*


# Expectations and Activities

Success in this class will depend upon your ability to: (1) think critically; (2) read and write University-level English prose; (3) develop an ability to understand and systematically apply the basics of research design; (4) work  independently and in group when needed. 

I expect students to: 

1) read this syllabus carefully,
2) log on to the class web site a minimum of four times each week,
3) read all assigned materials,
4) watch lectures,
5) submit assignments and exams on time,

DO NOT enroll in an online course if you know that you are going to be away from your Internet access for more than 5 or 6 days during the length of the course.  Unless you have an extenuating circumstance,  you have to submit all the assignments by the deadline.  

Please note that students are responsible for their own Internet access and computing resources. A loss of connectivity is not an excuse for late assignments. Some Internet service providers (ISPs) are notorious for inferior, unreliable service. In previous semesters, students have lost Internet connectivity in the middle of exams. Students who wait until the last possible moment to submit an assignment also run the risk of an unanticipated service disruption that prevents timely submission. 

I will post announcements on CANVAS on a regular basis. They will appear on your dashboard when you log in and/or will be sent to you directly through your preferred method of notification from CANVAS. Please make sure to check them regularly, as they will contain any important information about upcoming projects or class concerns. 

In this course we will use the CONVERSATIONS feature on the help corner (located in navigation links) to send email for private messages. You can either check your messages in the CANVAS system or set your notifications to your preferred method of contact. Please check your messages regularly. 

I receive many emails from students everyday, and I try to respond to all of them in a timely manner.  An email is a formal communication between you and your professor, and it thus should be addressed properly.  For my students, I am Dr. Bejar or Dr. Bejar-Lopez.  Please keep this in mind when you send me an email.  **I will not respond to emails that are not properly addressed.**

# Creating an Environment of Mutual Respect

This class is a partnership between you, your classmates and your professor. Together, we will build a supportive, respective, and productive environment to learn and to explore challenging questions about International Political Economy. Building this kind of environment requires mutual respect.

What do I expect from you, to create an environment of mutual respect? I expect you to complete the readings and watch all the posted lectures.  I also expect professional behavior in the class and to remain engaged throughout the semester.  Lack of interest or engagement is likely to be reflected in your grade.  

What can you expect from me? You can expect me to be tirelessly enthusiastic and to work hard for you, both in this semester and in future semesters if needed. I encourage all of you to stop by my virtual office hours, even if you don’t have a question and just would like to chat about the class, life after SJSU or life in general. You can reach me best via email at <sergio.bejar@sjsu.edu>. 


# Department of Political Science Learning Outcomes

1. Breadth: Students should possess a broad knowledge of the theory and methods of the various branches of the discipline.
2. Application and Disciplinary Methods: Students should be able to formulate research questions, engage in systematic literature searches using primary and secondary sources, evaluate research studies, and critically analyze and interpret influential political texts. Students should be able to apply these techniques to identify, understand, and analyze domestic and international political issues and organizations.
3. Communication Skills: Students should master basic competencies in oral and written communication skills and be able to apply these skills in the context of political science. This means communicating effectively about politics and/or public administration, public policy, and law.
4. Citizenship: Students should acquire an understanding of the role of the citizen in local, state, national, and global contexts and appreciate the importance of lifelong participation in political processes.


# Course Learning Outcomes 

Upon successful completion of this course, students will be able to: 

1. Understand how politics and economics intersect to produce different policies and outcomes;
2. Identify the most important issues in the current economic system;
3. Evaluate the outcomes of globalization and other economic policies;
4. Compare and contrast different theoretical explanations of phenomena occurring in the international economy.


# E-mail Policy

I am usually quick to respond to student e-mails. However, student e-mails tend to do several things that try my patience. I have a new policy, effective Spring 2021, that outlines why I will not respond to certain e-mails students send. Multiple rationales follow.

1. The student could answer his/her own inquiry by reading the syllabus.
2. The student missed assignments or exams for which there. I do not need to know the exact reason for a missed assignment or exam. Students with excusable reasons are responsible for giving me a note *in hard copy* that documents the reason for the missed class. 
3. The student wants to know what topics have been covered in class. The answer is always "you missed what was on the syllabus."
4. The student is protesting a grade without reference to specific points of objection. These e-mails tend to be expressive utility on the part of the student and do not require a response from me. Students interested in improving their knowledge of material should see me during office hours.
6. The student is requesting an extension on an assignment for which the syllabus already established the deadline. The answer is always "no".
7. The student is ["grade grubbing"](https://www.math.uh.edu/~tomforde/GradeGrubbing.html) or asking to round up a grade. The answer is always "no".
8. The student is asking for an extra credit opportunity, a request that amounts to more grading for the professor. The answer is "no".

# Course Workload Expectations: Succeeding in a Four-Unit Course

SJSU classes are designed such that in order to be successful, it is expected that students will spend a minimum of forty-five hours for each unit of credit (normally three hours per unit per week), including preparing for class, participating in course activities, completing assignments, and so on. Because this is a four-unit course, you can expect to spend a minimum of nine hours per week, in addition to time spent in class, on scheduled tutorials, assignments, or activities. This additional unit will allow for more in-depth investigation and engagement with course topics. Careful time management will help you keep up with readings and assignments and enable you to be successful in all of your courses. More details about student workload can be found in University Policy S12-3 at <http://www.sjsu.edu/senate/docs/S12-3.pdf>.
